/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S_market;

import ConDB.DBConn;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author A7meD3H
 */
public final class login extends javax.swing.JDialog {

    DBConn db = new DBConn();
    Main ma = new Main();
    Casher ca = new Casher();
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int x = 10;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setModal(true);

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_sh = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        co_role = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("شاشة الدخول");
        setBackground(new java.awt.Color(255, 255, 153));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(22, 160, 133));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("شركة ازو للتكنلوجيا");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel4)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(290, 290, 290))
        );

        jPanel2.setBackground(new java.awt.Color(26, 188, 156));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_username.setBackground(new java.awt.Color(240, 240, 240));
        txt_username.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_username.setForeground(new java.awt.Color(26, 188, 156));
        txt_username.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("كلمة المرور");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("أسم المستخدم");

        txt_sh.setBackground(new java.awt.Color(240, 240, 240));
        txt_sh.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_sh.setForeground(new java.awt.Color(26, 188, 156));
        txt_sh.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_sh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        txt_sh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_shActionPerformed(evt);
            }
        });

        txt_pass.setBackground(new java.awt.Color(240, 240, 240));
        txt_pass.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txt_pass.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        co_role.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        co_role.setForeground(new java.awt.Color(26, 188, 156));
        co_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "مدير", "1", "2", "3", "4" }));
        co_role.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        co_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                co_roleActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("الدخول كـ");

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(26, 188, 156));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Exit_Sign_32px.png"))); // NOI18N
        jButton2.setText("خروج");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(26, 188, 156));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Log Out_24x24.png"))); // NOI18N
        jButton1.setText("دخول");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(co_role, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addGap(38, 38, 38))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(co_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel2});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:.
        int Ahmed = JOptionPane.showConfirmDialog(null, "هل تريد الخروج ", "خروج", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (Ahmed == 0) {
            out out = new out();
            out.out();

            this.setVisible(false);
            this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ResultSet rs = null;

        rs = db.selecte("tb_user", new String[]{"username", "job","check_Discount", "check_Retriever", "check_Emp", "check_user",
            "check_Damaged", "check_Payouts", "check_Expenses", "check_Rep", "check_Accounts", "check_Ad_pr_ma_pr", "check_Wh_sales",
            "check_Inventory", "check_bu_pro", "check_Units", "check_Cat_Dep_Gro", "check_Baecod"},
                new String[]{"username", "pass"},
                new String[]{txt_username.getText(), txt_sh.getText()}, "=", "and");
        String namelogin = ""; //int id=0; 
        String jo = "";
        //int membertayp =0;
        int c_d = 0;
        int c_r = 0;
        int c_e = 0;
        int c_u = 0;
        int c_dam = 0;
        int c_p = 0;
        int c_exp = 0;
        int c_rep = 0;
        int c_Acc = 0;
        int c_m_p = 0;
        int check_w_sa = 0;
        int c_In = 0;
        int c_b_pr = 0;
        int c_Units = 0;
        int c_ca_de_gr = 0;
        int c_bar = 0;
        try {
            if (rs.next()) {
                namelogin = rs.getString("username");
                jo = rs.getString("job");
                c_d = rs.getInt("check_Discount");
                c_r = rs.getInt("check_Retriever");
                c_e = rs.getInt("check_Emp");
                c_u = rs.getInt("check_user");
                c_dam = rs.getInt("check_Damaged");
                c_p = rs.getInt("check_Payouts");
                c_exp = rs.getInt("check_Expenses");
                c_rep = rs.getInt("check_Rep");
                c_Acc = rs.getInt("check_Accounts");
                c_m_p = rs.getInt("check_Ad_pr_ma_pr");
                check_w_sa = rs.getInt("check_Wh_sales");
                c_In = rs.getInt("check_Inventory");
                c_b_pr = rs.getInt("check_bu_pro");
                c_Units = rs.getInt("check_Units");
                c_ca_de_gr = rs.getInt("check_Cat_Dep_Gro");
                c_bar = rs.getInt("check_Baecod");
                //id = rs.getInt("id_user");
                
                 ma.setnamelog(namelogin);
                
                if(jo.equals("كاشير")){
                    dispose();
                    ca.setVisible(true);
                    
                }
                else{
                

               
                
                if(c_d == 0){
                    ma.SetjPan22(false);
                }
                   if(c_ca_de_gr ==0 ){
                 ma.SetjPan13(false);
                 ma.SetjPan14(false);
                 ma.SetjPan15(false);
        
              }
             if(check_w_sa == 0){
                  ma.SetjPan2(false);
                 ma.SetjPan3(false);
             }
             
             
             if(c_u == 0){
                 ma.SetjPan17(false);
                 
             }

                //  mf.setusername(membernaem);
                //mf.setid(String.valueOf(id));
                //    get_usernam getUser = new get_usernam(membernaem);
                dispose();

                ma.setVisible(true);
            }
            } else {

                JOptionPane.showMessageDialog(null, "تأكد من ادخال الاسم و كلمة المرور صحيحه");

            }

          
             
           
             
        } catch (SQLException ex) {
            //   Logger.getLogger(logen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /*

        try {
            if(conn == null  || conn.isClosed() || rs.isClosed() || pst.isClosed()){conn = DB.jave_db();}
            int count = 0;    
            String sql = "select *  from ADusers where ADuser='" + txt_username.getText() + "' and ADpass='" + txt_pass.getText() + "'and ADrole='" + co_role.getSelectedItem().toString() + "'";

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("ADuser").equals(txt_username.getText()) && rs.getString("ADrole").equals(co_role.getSelectedItem().toString()) && rs.getString("ADpass").equals(txt_pass.getText())) {

                    int id = rs.getInt(1);
                    String username = rs.getString("ADuser");
                    String userd = rs.getString("ADrole");
                    String fusername = rs.getString("username");
                    User_d.userid = id;
                    User_d.username = username;
                    User_d.userd = userd;
                    User_d.fusername = fusername;
                    count = count + 1;

                    String access = (co_role.getSelectedItem().toString());

                    JOptionPane.showMessageDialog(null, " مرحباً ! " + fusername);
                    this.dispose();
                    new main2().setVisible(true);

                    Date date = GregorianCalendar.getInstance().getTime();
                    DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
                    String datestring = df.format(date);

                    Date d = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("HH:MM:SS");
                    String timestring = sdf.format(d);

                    String value0 = timestring;
                    String values = datestring;

                    int userid = User_d.userid;
                    username = User_d.username;
                    fusername = User_d.fusername;
                    userd = User_d.userd;

                    String sql1 = "insert into loginuser "
                            + "(user_id,user_name,dol,date,status)" + " values ('" + userid + "','" + fusername + "','" + userd + "','" + values + "-" + value0 + "','دخول')";

                    pst = conn.prepareStatement(sql1);
                    pst.execute();
                } else {
                    JOptionPane.showMessageDialog(null, "خطأ في اسم المستخدم او كلمة المرور");
                }
            } else {
                JOptionPane.showMessageDialog(null, "خطأ في اسم المستخدم او كلمة المرور");
            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                rs.close();
                pst.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
         */

    }//GEN-LAST:event_jButton1ActionPerformed

    private void co_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_co_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_co_roleActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_shActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_shActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_shActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3MouseReleased

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        if (x == 10) {

            txt_sh.setVisible(true);
            txt_pass.setVisible(false);

            String a = txt_pass.getText();
            txt_sh.setText(a);

            x++;

        }
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        if (x == 11) {
            txt_pass.setVisible(true);
            txt_sh.setVisible(false);
            String a = txt_sh.getText();
            txt_pass.setText(a);
            x--;
        }


    }//GEN-LAST:event_jButton3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> co_role;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_sh;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
